use AirportWebsite;

INSERT INTO Airport VALUES ('JFK', 'John F. Kennedy International Airport', 'United States', 'New York', 'New York City');
INSERT INTO Airport VALUES ('ORD', 'O''Hare International Airport', 'United States', 'Illinois', 'Chicago');
INSERT INTO Airport VALUES ('SFO', 'San Francisco International Airport', 'United States', 'California', 'San Francisco');
INSERT INTO Airport VALUES ('DFW', 'Dallas/Fort Worth International Airport', 'United States', 'Texas', 'Dallas');
INSERT INTO Airport VALUES ('LHR', 'Heathrow Airport', 'United Kingdom', '', 'London');
INSERT INTO Airport VALUES ('CDG', 'Charles de Gaulle Airport', 'France', '', 'Paris');
INSERT INTO Airport VALUES ('FRA', 'Frankfurt Airport', 'Germany', '', 'Frankfurt');
INSERT INTO Airport VALUES ('DXB', 'Dubai International Airport', 'United Arab Emirates', '', 'Dubai');
INSERT INTO Airport VALUES ('NRT', 'Narita International Airport', 'Japan', 'Chiba Prefecture', 'Narita');
INSERT INTO Airport VALUES ('HND', 'Haneda Airport', 'Japan', 'Tokyo', 'Tokyo');
INSERT INTO Airport VALUES ('SIN', 'Singapore Changi Airport', 'Singapore', '', 'Singapore');
INSERT INTO Airport VALUES ('HKG', 'Hong Kong International Airport', 'China', '', 'Hong Kong');
INSERT INTO Airport VALUES ('PVG', 'Shanghai Pudong International Airport', 'China', 'Shanghai', 'Shanghai');
INSERT INTO Airport VALUES ('MEL', 'Melbourne Airport', 'Australia', 'Victoria', 'Melbourne');
INSERT INTO Airport VALUES ('SYD', 'Sydney Airport', 'Australia', 'New South Wales', 'Sydney');
INSERT INTO Airport VALUES ('BOM', 'Chhatrapati Shivaji Maharaj International Airport', 'India', 'Maharashtra', 'Mumbai');
INSERT INTO Airport VALUES ('DEL', 'Indira Gandhi International Airport', 'India', 'Delhi', 'Delhi');
INSERT INTO Airport VALUES ('FJK', 'Fujikawaguchiko Airport', 'Japan', 'Yamanashi Prefecture', 'Fujikawaguchiko');
INSERT INTO Airport VALUES ('PTP', 'Pointe-à-Pitre Le Raizet Airport', 'Guadeloupe', '', 'Pointe-à-Pitre');
INSERT INTO Airport VALUES ('SJU', 'Luis Muñoz Marín International Airport', 'Puerto Rico', '', 'San Juan');
INSERT INTO Airport VALUES ('MEX', 'Mexico City International Airport', 'Mexico', 'Mexico City', 'Mexico City');
INSERT INTO Airport VALUES ('CTS', 'New Chitose Airport', 'Japan', 'Hokkaido', 'Chitose');
INSERT INTO Airport VALUES ('TPE', 'Taiwan Taoyuan International Airport', 'Taiwan', 'Taipei County', 'Taipei');
INSERT INTO Airport VALUES ('KIX', 'Kansai International Airport', 'Japan', 'Osaka Prefecture', 'Osaka');
INSERT INTO Airport VALUES ('ICN', 'Incheon International Airport', 'South Korea', 'Gyeonggi Province', 'Incheon');
INSERT INTO Airport VALUES ('MAD', 'Madrid-Barajas Airport', 'Spain', '', 'Madrid');
INSERT INTO Airport VALUES ('DOH', 'Hamad International Airport', 'Qatar', '', 'Doha');
INSERT INTO Airport VALUES ('BKK', 'Suvarnabhumi Airport', 'Thailand', '', 'Bangkok');
INSERT INTO Airport VALUES ('SVO', 'Sheremetyevo International Airport', 'Russia', 'Moscow Oblast', 'Moscow');
INSERT INTO Airport VALUES ('KBP', 'Boryspil International Airport', 'Ukraine', 'Kiev Oblast', 'Boryspil');